#!/usr/bin/env bash

# looks for common video formats in look_folder folder and create links in
# save_folder folder
# replaces /, single quote, space with _ to create links

look_folder="Pictures"
save_folder="links/"

rm -rf "$save_folder"
mkdir "$save_folder"

find "$look_folder" -regextype awk -iregex '.*\.(mp4|avi|3gp|mpeg|wmv)' -type f |

awk -v save_folder="$save_folder" '
# need a non-existent field separator so that awk does not split on spaces
# in file names
BEGIN { FS = ":"}
# need a copy of file name build a link name
{ $2 = $1 }
# replace /, single quote, 1 or more spaces with _
{ gsub("/", "_", $2) }
{ gsub(" +", "_", $2) }
{ gsub("\047", "_", $2) }
{ print "\"" $1 "\"", save_folder $2}
' |

xargs -L 1 ln

